   version: "3.9"

   services:
     django:
       container_name: api
       build:
         context: ./backend
       env_file:
         - ./backend/.env
       ports:
         - 8000:8000
       volumes:
         - ./backend:/backend
       depends_on:
         - psql
     psql:
       container_name: db
       image: "postgres:14.5-alpine"
       environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=admin
         - POSTGRES_PASSWORD=123456
     react:
       container_name: app
       build:
         context: ./frontend
       ports:
         - 3000:3000
       volumes:
         - ./frontend/src:/frontend/src